#!/bin/bash

go test -i libertymail-go/bits/hashing/ripemd160
go test -i libertymail-go/bits/hashing
go test -i libertymail-go/bits/encoding/base58
go test -i libertymail-go/bits/encoding/wif
go test -i libertymail-go/bits/random
go test -i libertymail-go/bits/crypt
go test -i libertymail-go/bits
go test -i libertymail-go/proto
go test -i libertymail-go/store
go test -i libertymail-go/grid
go test -i libertymail-go/api

go test libertymail-go/bits/hashing/ripemd160
go test libertymail-go/bits/hashing
go test libertymail-go/bits/encoding/base58
go test libertymail-go/bits/encoding/wif
go test libertymail-go/bits/random
go test libertymail-go/bits/crypt
go test libertymail-go/bits
go test libertymail-go/proto
go test libertymail-go/store
go test libertymail-go/grid
go test libertymail-go/api
